name: pull-request

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm install
          npm test
      - uses: checkity/upload@v1
        with:
          file-pattern: '**/lcov.info'
          repo-token: ${{ secrets.GITHUB_TOKEN }}